version: '3.8'

services:
  postgres-test:
    image: postgres:15-alpine
    container_name: tactical-card-game-test-db
    environment:
      POSTGRES_DB: tactical_card_game
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
    ports:
      - "5433:5432"
    volumes:
      - test_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U testuser -d tactical_card_game"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  test_postgres_data: